- name: 循环遍历vm配置信息, 用每个vm信息关闭一个vagrant虚拟机
  hosts: provider
  tasks:
    - name: 关闭vagrant虚拟机
      include_tasks: ansible_framework/tasks/stop_vagrant_instance.yml
      loop: "{{ vagrants }}"
      loop_control:
        index_var: 'idx'

#    - name: 关闭docker容器
#      include_tasks: ansible_framework/tasks/stop_docker_container.yml
#      loop: "{{ dockers }}"
#      loop_control:
#        index_var: 'idx'
