- name: 循环遍历vm配置信息, 用每个vm信息删除一个vagrant虚拟机
  hosts: provider
  tasks:
    - name: 删除vagrant虚拟机
      include_tasks: ansible_framework/tasks/remove_vagrant_instance.yml
      loop: "{{ vagrants }}"
      loop_control:
        index_var: 'idx'

#    - name: 删除docker容器
#      include_tasks: ansible_framework/tasks/remove_docker_container.yml
#      loop: "{{ dockers }}"
#      loop_control:
#        index_var: 'idx'
