- name: 循环遍历vm配置信息, 用每个vm信息创建一个vagrant虚拟机并启动
  hosts: provider
  tasks:
    - name: 创建vagrant虚拟机
      include_tasks: ansible_framework/tasks/setup_vagrant_instance.yml
      loop: "{{ vagrants }}"
      loop_control:
        index_var: 'idx'

#    - name: 创建docker容器
#      include_tasks: ansible_framework/tasks/setup_docker_container.yml
#      loop: "{{ dockers }}"
#      loop_control:
#        index_var: 'idx'
